# Generated by Django 2.1.3 on 2018-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Books',
        ),
    ]
